id: mobile-app-exits
displayName: Mobile Application Exit Info
description: |
  Insights into the different reasons surrounding the app's termination such as crashes, ANRs, native crashes etc.
icon: logo.svg
install:
  primary:
    link:
      url: https://www.newrelic.com
keywords:
  - Mobile
  - Application exit info
  - Mobile application exit
  - Exit info
  - Applicaiton not responding
categoryTerms:
  - Mobile 
 
